name: gis_gz_environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - gdal==2.4.1
  - matplotlib==3.1.2
  - pandas
  - geopandas
  - numpy
  - networkx==2.2
  - rasterio==1.0.23
  - fiona
  - shapely==1.6.4
  - scipy
  - scikit-learn
  - descartes