name: gis_gz_environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - gdal==2.4.1
  - matplotlib==3.1.2
  - pandas==0.25.1
  - geopandas==0.1.1
  - numpy==1.15.2
  - networkx==2.2
  - rasterio==1.0.23
  - fiona==1.8.6
  - shapely==1.6.4
  - scipy==1.1.0
  - scikit-learn==0.21.3
  - descartes==1.1.0