name: gis_gz_environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - pandas
  - geopandas
  - matplotlib
  - numpy
  - networkx==2.2
  - rasterio
  - fiona
  - shapely
  - scipy
  - scikit-learn
  - ipywidgets
  - descartes