name: gis_gz_environment
channels:
  - conda-forge
dependencies:
  - python=3.6
  - gdal==2.4.1
  - matplotlib==3.1.2
  - pandas==0.25.3
  - geopandas==0.6.2
  - numpy==1.17.3
  - networkx==2.2
  - rasterio==1.0.23
  - fiona==1.8.6
  - shapely==1.6.4
  - scipy==1.3.1
  - scikit-learn==0.22.1
  - descartes==1.1.0