import matplotlib.pyplot as plt


def show_results(df, data_categories, number_of_categories, title):
    """
    Plots the results by using matplotlib
    :param df: The original DataFrame
    :param data_categories: The object generated by the PySAL categorization function
    :param number_of_categories: The number of categories used
    :param title: The title that should be shown on the top of the map
    :return:
    """
    fig, ax = plt.subplots(figsize=(12, 10), subplot_kw={'aspect': 'equal'})
    df.assign(cl=data_categories.yb).plot(column='cl',
                                          categorical=True,
                                          k=number_of_categories,
                                          cmap='OrRd',
                                          linewidth=0.1,
                                          ax=ax,
                                          edgecolor='white',
                                          legend=True)

    ax.set_axis_off()
    plt.title(title)

    return